### ISSUE TITLE
Future JavaScript Now - iterators

### ISSUE THREAD

**Issue by msusur** [CodeFiction/typescript-book#11]
https://github.com/CodeFiction/typescript-book/blob/master/docs/iterators.md

**Comment by vceylan** [comment]
Selam,
Ben bu kısmın çevirisiyle ilgilenebilirim. Üzerime atayabilirsiniz.
Kolay Gelsin.

**Comment by msusur** [comment]
PR gonderdikten sonra seni de takima ekleyecegim @vceylan, ondan sonra sana atayabilirim. :1st_place_medal:

**Comment by msusur** [comment]
#33 ile kapanacak.
