### ISSUE TITLE
Etiketler için önerilerim

### ISSUE THREAD

**Issue by UgurAldanmaz** [CodeFiction/typescript-book#23]
Etiketler küçük harflerden oluşabilir.

* Çeviri işleri için ->  Çeviri Gerekiyor yerine çeviri
* Çevirisi üstlenilmiş işler için -> çevirisi yapılıyor
* Diğer varsayılan olarak gelen etiketlerin silinmesi (bug, wontfix, vs.)
   * Yerlerine şu etiketlerin oluşturulması:
   * çeviri hatası
   * mükerrer
   * iyileştirme
   * soru
* Takım dışındaki katılımcıların, yani yeni başlayacak kişilerin giriş yapmasına yardımcı olacak kolay işler için -> herkese açık (İngilizcesi up for grabs olan bu etiketin çevirisi garipmiş :D)

**Comment by ozgunbal** [comment]
Mükerrer yerine tekrar eden kullanılmasını öneriyorum. Bana kalırsa çok sırıtmıyorsa arapça kökenlisi yerine yeni türkçe olanı tercih etmek daha mantıklı.

**Comment by msusur** [comment]
güzel fikir, düzenledim. @ozgunbal 👍
