### ISSUE TITLE
Future JavaScript Now - Classes

### ISSUE THREAD

**Issue by msusur** [CodeFiction/typescript-book#4]
- [x] https://github.com/CodeFiction/typescript-book/blob/master/docs/classes.md
- [x] https://github.com/CodeFiction/typescript-book/blob/master/docs/classes-emit.md
- [x] https://github.com/CodeFiction/typescript-book/blob/master/docs/classes-extensibility.md
- [x] https://github.com/CodeFiction/typescript-book/blob/master/docs/classes-super.md

**Comment by mustafadinler** [comment]
Classes basligi altindaki dosyalar icin issue yoktu ekledim

**Comment by uguratar** [comment]
@mustafadinler yarattığın issueları göremedim ya da olayı anlamadım. Buradaki 4 kaynaktan bazılarını ben de çevirebilirim ama sen classes.md dosyasına başlamışsın. Buradan onun durumunu anlamak çok zor. Belki buradaki dört kaynak için buraya güncelleme geçebiliriz.

**Comment by mustafadinler** [comment]
@uguratar bahettigim de oydu, mert sadece issue olustururken icerigine 
https://github.com/CodeFiction/typescript-book/blob/master/docs/classes.md 
file'ini eklemisti.
classes section'undaki diger md file'larda beni ilgilendiriyordur diye bu issue'nun icerigine o dosyalari cevirilecek diye ekledim. Yani issue yaratmadim, varolana 3 md file ekledim. Ama dedigin gibi parcalayayip farkli issue mu yaratmaliydik her md file'i onu sormustum. Simdilik bunlari ben ceviririm ama daha sonrasi icin sormustum nasil ilerlenecek diye.  Ben tik koydum yanlarina bittikce tiklerim ama ne kadar goze carpar bilemedim.
