### ISSUE TITLE
Which files?

### ISSUE THREAD

**Issue by ozgunbal** [CodeFiction/typescript-book#54]
https://github.com/CodeFiction/typescript-book/blob/master/docs/project/files.md

**Comment by msusur** [comment]
Bence, eger zaman bulabilirse, bunu da @mustafadinler cevirse ayni chapter icinde daha tutarli bir ceviri olmus olur. Ne dersin? Yoksa ben de alabilirim.

**Comment by ozgunbal** [comment]
Bu durumda tüm project chapter'ını @mustafadinler 'e çevirtmiş oluyoruz :smile:

**Comment by msusur** [comment]
Ama o da cok guzel ceviriyor! Saka bir yana tabi eger vaktin yoksa direk bana atayabilirsin @mustafadinler o konuda bir problem yok :)

**Comment by mustafadinler** [comment]
tamamdır gazı aldım:) bu issue'yu da aldım üstüme. Milestone'a yetiştiririm gibi üstümdeki issue'ları ama çevirmek isteyen çekinmeden kendi üstüne alabilir.
