### ISSUE TITLE
Future JavaScript Now - Rest Parameters

### ISSUE THREAD

**Issue by msusur** [CodeFiction/typescript-book#6]
https://github.com/CodeFiction/typescript-book/blob/master/docs/rest-parameters.md

**Comment by UgurAldanmaz** [comment]
Bunu bana atayabilir misiniz?

**Comment by uguratar** [comment]
Burada neler oldu? Bunu merge etmeli miyiz? @tugrulcan  ya da merge ettiysek bu issue'yu kapatmalı mıyız?

**Comment by UgurAldanmaz** [comment]
@uguratar Sanırım Tuğrulcan benim pull requestim üzerinde bir değişiklik yapmış. Aslında ben de tam olarak ne olduğunu halen anlamadım :)

**Comment by msusur** [comment]
Peki ne yapiyoruz simdi :) @UgurAldanmaz @uguratar ve @tugrulcan ??

**Comment by UgurAldanmaz** [comment]
[Pull request](https://github.com/CodeFiction/typescript-book/pull/25) merge edilmiş. Issue'u kapatmamız yeterli.
